@host = http://localhost:3000
@createdInvestmentId = {{createdInvestment.response.body.$.id}}
@createdUserId = {{createdUser.response.body.$.id}}
@categoryPosId = {{categoryPos.response.body.$.id}}
@token = {{signin.response.body.$.token}}

### Create User

# @name createdUser
POST {{host}}/api/users
Content-Type: application/json

{
  "name": "Luiz",
  "email": "luiz@email.com",
  "password": "12345678"
}

### Signin 401

# @name signin
POST {{host}}/api/signin
Content-Type: application/json

{
  "email": "luiz@email.com",
  "password": "321"
}

### Signin Ok

# @name signin
POST {{host}}/api/signin
Content-Type: application/json

{
  "email": "luiz@email.com",
  "password": "12345678"
}

### Read User (whitout token)

GET {{host}}/api/users/me

### Read User (with token)

GET {{host}}/api/users/me
Authorization: bearer {{token}}

### Read Categories

GET {{host}}/api/categories
Authorization: bearer {{token}}

### Read Category Pós

# @name categoryPos
GET {{host}}/api/categories?name=Pós
Authorization: bearer {{token}}

### Read Category IPCA

# @name categoryIpca
GET {{host}}/api/categories?name=IPCA
Authorization: bearer {{token}}

### Create Investment

@categoryIpcaId = {{categoryIpca.response.body.$.id}}

# @name createdInvestment
POST {{host}}/api/investments
Authorization: bearer {{token}}
Content-Type: application/json

{
  "name": "Tesouro Selic 2029",
  "value": 10000,
  "categoryId": "{{categoryIpcaId}}",
  "userId": "{{createdUserId}}"
}

### Read Investments

GET {{host}}/api/investments
Authorization: bearer {{token}}

### Read Investments by Name

GET {{host}}/api/investments?name=Tesouro
Authorization: bearer {{token}}

### Read Investments by Id

GET {{host}}/api/investments/{{createdInvestmentId}}
Authorization: bearer {{token}}

### Update Investment

@categoryPosId = {{categoryPos.response.body.$.id}}

PUT {{host}}/api/investments/{{createdInvestmentId}}
Authorization: bearer {{token}}
Content-Type: application/json

{
  "name": "Tesouro Selic 2029",
  "value": 20000,
  "categoryId": "{{categoryPosId}}",
  "userId": "{{createdUserId}}"
}

### Delete Investment

DELETE {{host}}/api/investments/{{createdInvestmentId}}
Authorization: bearer {{token}}
